services:
  data-setup:
    container_name: ia-alzheimer-setup
    build:
      context: ./training
      dockerfile: Dockerfile.setup
    image: model-alzheimer-setup:latest
    volumes:
      - ./shared:/app/shared
      - ./training/kaggle.json:/app/kaggle.json:ro
    command: ["python", "-m", "scripts.prepare_data"]
    networks:
      - alzheimer-network

  alzheimer-binary:
    container_name: ia-alzheimer-binary
    build:
      context: ./training
      dockerfile: Dockerfile.binary
    image: model-alzheimer-binary:latest
    runtime: nvidia
    depends_on:
      data-setup:
        condition: service_completed_successfully
    env_file:
      - ./training/.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - WANDB_SILENT=true
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/app/shared
      - ./training/configs:/app/configs:ro
      - ./training/kaggle.json:/app/kaggle.json:ro
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - alzheimer-network

  alzheimer-multiclass:
    container_name: ia-alzheimer-multiclass
    build:
      context: ./training
      dockerfile: Dockerfile.multiclass
    image: model-alzheimer-multiclass:latest
    runtime: nvidia
    depends_on:
      data-setup:
        condition: service_completed_successfully
    env_file:
      - ./training/.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - WANDB_SILENT=true
    ports:
      - "8081:8080"
    volumes:
      - ./shared:/app/shared
      - ./training/configs:/app/configs:ro
      - ./training/kaggle.json:/app/kaggle.json:ro
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - alzheimer-network

volumes:
  shared-data:
    driver: local

networks:
  alzheimer-network:
    driver: bridge