FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-runtime

# Diretório de trabalho
WORKDIR /app

# Variáveis de ambiente
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONIOENCODING=utf-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libsm6 libxext6 libxrender-dev ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copiar requisitos e instalar dependências (removendo torch redundante)
COPY requirements.txt .
RUN sed -i '/torch/d' requirements.txt && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    rm -rf /root/.cache/pip

# Copiar apenas o código-fonte (filtrado pelo .dockerignore)
COPY . .

# Comando padrão
CMD ["python", "-m", "scripts.train_multiclass"]
